### ISSUE TITLE
Deploy to Maven central

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Rustemt/metadata-extractor#39]
```
To simplify for users of build tools with dependency management (like Maven, 
Ivy, etc), it would greatly simplify for users of your library if you would 
deploy to Maven central.
Sonatype provides repository support free of charge to facilitate for all this. 
Please read more here:
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage
+Guide

This process is simpler for you if you use Maven, but it is not a requirement.

v2.4.0 beta exists in central, but 2.3.1 and the RCs for 2.5.0 is currently 
missing.
```

Original issue reported on code.google.com by `anders.g...@gmail.com` on 1 Dec 2011 at 12:38

**Comment by GoogleCodeExporter** [comment]
```
I took metadata-extractor-2.5.0-RC3-src and turned it into a standard Maven 
project. I also embedded the xmp source so it can be deployed as a stand-alone 
jar.  All tests pass. Source attached.  richard at HotSpringsFinder.com
```

Original comment by `reast...@gmail.com` on 16 Jan 2012 at 6:16

Attachments:
- [metadata-extractor-2.5.0-RC3-Maven.zip](https://storage.googleapis.com/google-code-attachments/metadata-extractor/issue-39/comment-1/metadata-extractor-2.5.0-RC3-Maven.zip)

**Comment by GoogleCodeExporter** [comment]
```
I would suggest that you keep them as two separated artifacts. Creating an 
über-jar will only cause issues later on. It always does.
```

Original comment by `anders.g...@gmail.com` on 16 Jan 2012 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
The xmp source can be removed and the following can be uncommented in the 
pom.xml:

        <!--
        <dependency>
            <groupId>com.adobe</groupId>
            <artifactId>xmp</artifactId>
            <version>0.0.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/xmpcore.jar</systemPath>
        </dependency>
         -->

but either way it's a hack until the two libraries committers start deploying 
to maven repositories. 
```

Original comment by `reast...@gmail.com` on 17 Jan 2012 at 12:00

**Comment by GoogleCodeExporter** [comment]
```
waiting for revision 2.6.0 in maven repository :)
```

Original comment by `mailsur...@gmail.com` on 24 May 2012 at 5:30

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I'd like to stress that the suggested solution with having a system scope 
dependency to the xmp artifact is not good. It will make it impossible for 
anyone to use an artifact with such a dependency. You will either ensure that 
the xmp artifact also gets uploaded to the Maven repo or include the source in 
your project build.
```

Original comment by `anders.g...@gmail.com` on 24 May 2012 at 9:04

**Comment by GoogleCodeExporter** [comment]
```
The first step in this is going to be to get Adobe's xmpcore.jar deployed into 
a Maven repo somewhere.

Again, I'm not familiar with Maven, but this page suggests that it can be 
uploaded by anyone:

https://docs.sonatype.org/display/Repository/Uploading+3rd-party+Artifacts+to+Th
e+Central+Repository

If someone wants to look at this, it would make the job of getting 
metadata-extractor onto Maven Central much simpler for me.

The Adobe source/binary is released under a BSD license:

http://www.adobe.com/devnet/xmp/library/eula-xmp-library-java.html
```

Original comment by `drewnoakes` on 29 May 2012 at 4:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `drewnoakes` on 29 May 2012 at 4:55
- Added labels: **Type-Task**, **Usability**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
An email from Jorg Ehrlich points out that the XMPCore library is available on 
Maven Central:

http://search.maven.org/#search%7Cga%7C1%7Cxmpcore 

It is the same version that is also available on the Adobe XMP SDK page:

http://www.adobe.com/devnet/xmp.html 

This is great news and should make listing metadata-extractor even easier.
```

Original comment by `drewnoakes` on 31 May 2012 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
Unfortunately that version of XMPCore is compiled with Java 7 and will result 
in these errors on Java 6:

java.lang.UnsupportedClassVersionError: com/adobe/xmp/XMPException : 
Unsupported major.minor version 51.0 


```

Original comment by `ebolw...@gmail.com` on 1 Jun 2012 at 8:54

**Comment by GoogleCodeExporter** [comment]
```
Issue 50 has been merged into this issue.
```

Original comment by `drewnoakes` on 4 Jun 2012 at 11:51

**Comment by GoogleCodeExporter** [comment]
```
The XMPCore is now available in the repo2 central maven repository in version 
5.1.1 that fixes the compilation issue with Java 7.

Just for information, I fetched the sources of metadata-extractor with git and 
I remarked the XMPCore sources available in Libraries/XMPCore aren't correct. 
Indeed, in 5.1.0 and 5.1.1 XMPPropertyInfo#getValue() returns a String instead 
of an Object instance.
```

Original comment by `miguel.m...@gmail.com` on 29 Jun 2012 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
The 5.1.1 version doesn't seem to work. I'm getting this error:

java.lang.NoSuchMethodError: 
com.adobe.xmp.properties.XMPPropertyInfo.getValue()Ljava/lang/Object;
    at com.drew.metadata.xmp.XmpReader.extract(Unknown Source)
    at com.drew.imaging.jpeg.JpegMetadataReader.extractMetadataFromJpegSegmentReader(Unknown Source)
    at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
    at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
    at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
    at com.barnesandnoble.phantom.Utils.loadMetadataFromFile(Utils.java:473)

```

Original comment by `kenne...@gmail.com` on 14 Jul 2012 at 12:15

**Comment by GoogleCodeExporter** [comment]
```
I've started the process of getting a Sonatype project setup: 
https://issues.sonatype.org/browse/OSSRH-3948
```

Original comment by `ray.ga...@alfresco.com` on 18 Jul 2012 at 9:59

**Comment by GoogleCodeExporter** [comment]
```
I've gotten this on Maven Central: http://search.maven.org/#browse%7C930506482

This will be a decent chunk of work for every release since we'll need to 
'mavenize' each time, unless some of the changes suggested/implemented by 
Farrukh Najmi, myself, and others are rolled into the base distribution.

Those could be as simple as a folder structure change and addition of a pom 
file so that the core developers can proceed with their normal build and test 
process, but that simple change would make life for Maven folks (and myself 
releasing to Sontype) MUCH easier.

I'm happy to help further if you'd like, perhaps work on the structure change 
to support both existing and Maven build processes?

Drew, are you open to adding more committers to this project?

Regards,

Ray
```

Original comment by `ray.ga...@alfresco.com` on 20 Jul 2012 at 8:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `drewnoakes` on 16 Oct 2012 at 3:47
- Added labels: **Priority-Critical**
- Removed labels: **Priority-High**

**Comment by GoogleCodeExporter** [comment]
Original comment by `drewnoakes` on 16 Oct 2012 at 5:03
- Added labels: **Component-Build**, **Component-Deployment**, **Milestone-2.7.0**, **Motive-Usability**
- Removed labels: **Usability**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Anyone working on a maven update for 2.6.4?  Thank you to Ray for building 
2.6.2.
-Lta
```

Original comment by `heymr.wi...@gmail.com` on 31 Jul 2013 at 3:00

**Comment by GoogleCodeExporter** [comment]
```
Ditto...please upload 2.6.4 to maven...it's been a year and the upload process 
should be part of the maven build script :-P
```

Original comment by `k...@mustbin.com` on 6 Feb 2014 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
I have been waiting that someone solve this problem since 2012.  but I think 
this project is dead. hmmm... I think I should look for another library... :-(

java.lang.NoSuchMethodError: 
com.adobe.xmp.properties.XMPPropertyInfo.getValue()Ljava/lang/Object;
    at com.drew.metadata.xmp.XmpReader.extract(Unknown Source)
    at com.drew.imaging.jpeg.JpegMetadataReader.extractMetadataFromJpegSegmentReader(Unknown Source)
    at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
    at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
    at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
    at com.barnesandnoble.phantom.Utils.loadMetadataFromFile(Utils.java:473)
```

Original comment by `hameedul...@gmail.com` on 19 Mar 2014 at 12:31

**Comment by GoogleCodeExporter** [comment]
```
I had the same problem and fixed it (at least for me)
I have downloaded the sources 
(https://code.google.com/p/metadata-extractor/downloads/detail?name=metadata-ext
ractor-2.6.4-src.jar&can=2&q=) and xmpcore5.1.1.jar 
(http://www.java2s.com/Code/JarDownload/xmpcore/xmpcore-5.1.1.jar.zip), 
recompiled the sources with JDK 1.6. and redeployed my Android app.
:-) 
Yeah, now I can read the IPTC / XMP tag of my images.

```

Original comment by `markus.h...@gmail.com` on 19 Mar 2014 at 9:34

**Comment by GoogleCodeExporter** [comment]
```
This issue has been migrated (along with the project) to GitHub:

https://github.com/drewnoakes/metadata-extractor/issues/1

Please comment on that issue, not here.
```

Original comment by `drewnoakes` on 19 Nov 2014 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
Version 2.7.0 is now available on Maven Central.
```

Original comment by `drewnoakes` on 7 Dec 2014 at 9:24
- Changed state: **Done**
